---
#銀行座標
bank-x: 228.5
bank-y: 9
bank-z: 232.5

#闇金野郎
name: "闇金"
debt-x: 250.1
debt-y: 8
debt-z: 217
id: 266
meta: 0

#手数料
fee: 100

#通帳作成の手数料
passbook-fee: 500

#通帳再発行の手数料 & 料金
reissue-passbook-fee: 10000

#借金で受け取れる最高金額
debt-amount: 50000
...